@startuml

class "トラック" as Track {
    テーマ
    会場
}

class "時間帯" as TimeBlock {
    番号
    開始時刻
    終了時刻
}

class "プログラム" as Program {
}

class "食事" as Meal {
    名称
}

class "講演" as Talk {
    タイトル
}

class "講演者" as Talker {
    名前
}

Program "1..*" -up- "1" Track
Program "1..*" -up- "1" TimeBlock

Program <|-- Talk
Program <|-- Meal

Talk "*" -- "1.*" Talker

@enduml
